{
 "title": "Consensus Round Handling",
 "tags": [ "Platform" ],
 "time": { "from": "2024-02-09T17:50:36.987Z", "to": "2024-02-11T21:57:23.869Z" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec,environment)"
    }
   },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "title": "Platform Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 } },
  { "title": "Flush", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Round Handling: keystone flush millis per round",
   "type": "timeseries",
   "description": "Average time to flush a round's keystone event to disk",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_keystoneFlushMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Handle Round", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Round Handling: data prop millis",
   "type": "timeseries",
   "description": "Average time to propagate consensus data to transactions, update platform state, and handle transactions",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_dataPropMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Hash Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Round Handling: handle millis per round",
   "type": "timeseries",
   "description": "Average time to pass state to the hash manager",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_handleMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Round Handling: store millis per round",
   "type": "timeseries",
   "description": "Average time to add consensus round events to signed state storage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_storeMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Hash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Round Handling: hash millis per round",
   "type": "timeseries",
   "description": "Average time spent hashing the consensus round events",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_hashMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Build State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Round Handling: build state millis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_buildStateMillis{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Expiring events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Round Handling: for sig clean millis",
   "type": "timeseries",
   "description": "Average time spent expiring signed state storage events",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_forSigCleanMillis{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Round Handling: total millis",
   "type": "timeseries",
   "description": "Average total time to handle a consensus round",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internal_consRound_total{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  }
 ]
}