{
 "title": "Data on disk",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU IO/wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode='iowait', environment=\"$environment\"}[$__rate_interval])",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "CPU Average Load over last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPUs" } },
   "targets": [
    {
     "expr": "node_load5{environment=\"$environment\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Java Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "platform_memTot{environment=\"$environment\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "Java Direct Usage (32GB available)",
   "type": "timeseries",
   "description": "Direct memory is manually managed and used for database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "platform_directMemInMB{environment=\"$environment\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "System Memory Used Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{environment=\"$environment\"} - node_memory_MemFree_bytes{environment=\"$environment\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "System Memory Disk Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{environment=\"$environment\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "System Memory Swap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{environment=\"$environment\"} - node_memory_SwapFree_bytes{environment=\"$environment\"})",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "System Memory Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgfault{environment=\"$environment\"}[$__rate_interval])",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  { "title": "Raw Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "bytes written per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{environment=\"$environment\"}[$__rate_interval])) by (node_id, environment) ",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "Time spent doing IO (sum of all disks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{environment=\"$environment\"}[$__rate_interval])) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "Weighted time spent doing IO (sum of all disks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_weighted_seconds_total{environment=\"$environment\"}[$__rate_interval])) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "Disk Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_weighted_seconds_total{environment=\"$environment\"}[$__rate_interval])) by (node_id, environment)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  { "title": "Merkle Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Time to write saved state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "platform_stateToDisk_ms{environment=\"$environment\",type=\"max\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "VirtualMap Combined Flush Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(virtual_map_vmap_lifecycle_flushDurationMs_accountStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushDurationMs_fileStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushDurationMs_smartContractIterableKvStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushDurationMs_tokenRelStore{environment=\"$environment\"}) by (environment,node_id) + sum(virtual_map_vmap_lifecycle_flushDurationMs_uniqueTokenStore{environment=\"$environment\"}) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "VirtualMap Combined Hash Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(virtual_map_vmap_lifecycle_hashDurationMs_accountStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_hashDurationMs_fileStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_hashDurationMs_smartContractIterableKvStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_hashDurationMs_tokenRelStore{environment=\"$environment\"}) by (environment,node_id) + sum(virtual_map_vmap_lifecycle_hashDurationMs_uniqueTokenStore{environment=\"$environment\"}) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "VirtualMap Combined Flush Backlog Size (SHOULD BE 0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(virtual_map_vmap_lifecycle_flushBacklogSize_accountStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushBacklogSize_fileStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushBacklogSize_smartContractIterableKvStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushBacklogSize_tokenRelStore{environment=\"$environment\"}) by (environment,node_id) + sum(virtual_map_vmap_lifecycle_flushBacklogSize_uniqueTokenStore{environment=\"$environment\"}) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "VirtualMap Combined Size Back Pressure (Ideally 0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(virtual_map_vmap_lifecycle_familySizeBackpressureMs_accountStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_familySizeBackpressureMs_fileStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_familySizeBackpressureMs_smartContractIterableKvStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_familySizeBackpressureMs_tokenRelStore{environment=\"$environment\"}) by (environment,node_id) + sum(virtual_map_vmap_lifecycle_familySizeBackpressureMs_uniqueTokenStore{environment=\"$environment\"}) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "VirtualMap Combined Back Pressure (Ideally 0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(virtual_map_vmap_lifecycle_flushBackpressureMs_accountStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushBackpressureMs_fileStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushBackpressureMs_smartContractIterableKvStore{environment=\"$environment\"}) by (environment, node_id) + sum(virtual_map_vmap_lifecycle_flushBackpressureMs_tokenRelStore{environment=\"$environment\"}) by (environment,node_id) + sum(virtual_map_vmap_lifecycle_flushBackpressureMs_uniqueTokenStore{environment=\"$environment\"}) by (environment, node_id)",
     "legendFormat": "node{{node_id}}"
    }
   ]
  }
 ]
}