{
 "title": "Event Creation",
 "tags": [ "Platform" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec,environment)"
    }
   },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Event creation manager: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "platform_eventCreationManager_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Event Creation Throttle Fractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Attempting Creation Fraction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_ATTEMPTING_CREATION_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "No Eligible Parents Fraction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_NO_ELIGIBLE_PARENTS_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Overloaded Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_OVERLOADED_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Paused Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_PAUSED_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Rate Limited Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_RATE_LIMITED_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Platform Status Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_PLATFORM_STATUS_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Pipeline Insertion Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_PIPELINE_INSERTION_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Pipeline Insertion Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "platform_eventCreation_fraction_PIPELINE_INSERTION_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  }
 ]
}