{
 "title": "Gossip",
 "tags": [ "Platform" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Environment", "label": "Environment", "query": { "query": "label_values(environment)" } },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "conns Changes",
   "type": "timeseries",
   "description": "The increase in the number of TLS connections established by a node per second.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(platform_conns{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__rate_interval])",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "placeholder", "type": "timeseries", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "dupEv%",
   "type": "timeseries",
   "description": "The number of events received per second that are already known.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "platform_dupEvPercent{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "dupEv%",
   "type": "gauge",
   "description": "The number of events received per second that are already known.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_dupEvPercent{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_dupEvPercent{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_dupEvPercent{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "dupEv/sec",
   "type": "timeseries",
   "description": "The number of events received per second that are already known.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "internal_dupEv_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "dupEv",
   "type": "gauge",
   "description": "The number of events received per second that are already known.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_dupEv_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_dupEv_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_dupEv_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "syncPermitsAvailable",
   "type": "timeseries",
   "description": "The number of sync permits available.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "platform_syncPermitsAvailable{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "syncPermitsAvailable",
   "type": "gauge",
   "description": "The number of sync permits available.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_syncPermitsAvailable{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_syncPermitsAvailable{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_syncPermitsAvailable{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "ev/syncR",
   "type": "timeseries",
   "description": "The number of events received per successful sync.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "platform_ev_per_syncR{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "ev/syncR",
   "type": "gauge",
   "description": "The number of events received per successful sync.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_ev_per_syncR{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_ev_per_syncR{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_ev_per_syncR{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "ev/syncS",
   "type": "timeseries",
   "description": "The number of events received per successful sync.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "platform_ev_per_syncS{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "syncGenDiff",
   "type": "timeseries",
   "description": "The number of generation ahead (positive) or behind (negative) when syncing.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "internal_syncGenDiff{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "syncs/sec",
   "type": "timeseries",
   "description": "The total number of syncs completed per second by each node.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "platform_syncs_per_sec_Hz{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "sec/sync",
   "type": "timeseries",
   "description": "The duration of average successful sync.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "internal_sec_per_sync{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "conns",
   "type": "timeseries",
   "description": "The number of times a TLS connections was created.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "platform_conns{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  }
 ]
}