{
 "title": "Hashgraph",
 "tags": [ "Platform" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec{environment!~\"nmt.*\"},environment)"
    }
   },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "rounds/sec",
   "type": "timeseries",
   "description": "The average number of rounds per second.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "platform_rounds_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "rounds/sec",
   "type": "gauge",
   "description": "The average number of rounds per second.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_rounds_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg rounds/sec"
    }
   ]
  },
  {
   "title": "events/round",
   "type": "timeseries",
   "description": "The average number of events per round.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "internal_events_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "events/round",
   "type": "gauge",
   "description": "The average number of events per round.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(internal_events_per_round{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "opAgeDiff",
   "type": "timeseries",
   "description": "The average age difference (in generations) between an event created by this node and its other parent.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "platform_opAgeDiff{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "opAgeDiff",
   "type": "gauge",
   "description": "The average age difference (in generations) between an event created by this node and its other parent.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_opAgeDiff{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "staleEv Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(internal_staleEvTot_total{environment=\"$network\", node_id=~\"$NodeID\"}[$__rate_interval])",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "placeholder", "type": "timeseries", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 } },
  {
   "title": "coinR",
   "type": "timeseries",
   "description": "The number of coin rounds that have occurred so far.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "internal_coinR{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "coinR",
   "type": "gauge",
   "description": "The number of coin rounds that have occurred so far.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(internal_coinR{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "tipsetAdvancement",
   "type": "timeseries",
   "description": "The score, based on tipset advancement weight, of each new event created by this node. A score of 0.0 means the an event has zero advancement weight, while a score of 1.0 means that the event had the maximum possible advancement weight.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "platform_tipsetAdvancement{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "tipsetAdvancement",
   "type": "gauge",
   "description": "The score, based on tipset advancement weight, of each new event created by this node. A score of 0.0 means the an event has zero advancement weight, while a score of 1.0 means that the event had the maximum possible advancement weight.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_tipsetAdvancement{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "bullyScore",
   "type": "timeseries",
   "description": "The score, based on tipset advancements, of how much this node is being selfish. Selfishness is defined as refusing to use another node's events as other parents.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "platform_selfishness{environment=\"$network\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  }
 ]
}