{
 "title": "Intake Pipeline",
 "tags": [ "Platform" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec,environment)"
    }
   },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Event hasher: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "platform_eventHasher_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Post hash collector: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "platform_postHashCollector_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Internal event validator: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "platform_internalEventValidator_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Event deduplicator: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "platform_eventDeduplicator_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Event signature validator: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "platform_eventSignatureValidator_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Orphan buffer: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "platform_orphanBuffer_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Orphan buffer: size",
   "type": "timeseries",
   "description": "Number of current orphan events",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "platform_orphanBufferSize_events{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "In order linker: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "platform_inOrderLinker_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Linked event intake: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "platform_linkedEventIntake_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Linked event intake: time waiting for transaction prehandle",
   "type": "timeseries",
   "description": "Average time waiting for transaction prehandle, in milliseconds",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "platform_timeWaitingForTransactionPrehandling_ms{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Consensus Events in queue",
   "type": "timeseries",
   "description": "Number of consensus events waiting to be handled",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "internal_consEvents{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "PCES writer: unhandled task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "platform_pcesWriter_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  }
 ]
}