{
 "title": "Multi Any Stat + Status",
 "description": "Multiple any stats, plus the platform status",
 "tags": [ "Platform" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "network", "label": "Network", "query": { "query": "label_values(environment)" } },
   { "name": "name1", "label": "Metric Name 1", "query": { "query": "label_values(__name__)" } },
   { "name": "name2", "label": "Metric Name 2", "query": { "query": "label_values(__name__)" } },
   { "name": "name3", "label": "Metric Name 3", "query": { "query": "label_values(__name__)" } },
   { "name": "name4", "label": "Metric Name 4", "query": { "query": "label_values(__name__)" } },
   { "name": "name5", "label": "Metric Name 5", "query": { "query": "label_values(__name__)" } },
   { "name": "metric1_type", "label": "Metric 1 Type", "query": "min,max,stddev,mean" },
   { "name": "metric2_type", "label": "Metric 2 Type", "query": "min,max,stddev,mean" },
   { "name": "metric3_type", "label": "Metric 3 Type", "query": "min,max,stddev,mean" },
   { "name": "metric4_type", "label": "Metric 4 Type", "query": "min,max,stddev,mean" },
   { "name": "metric5_type", "label": "Metric 5 Type", "query": "min,max,stddev,mean" }
  ]
 },
 "panels": [
  { "title": "Platform Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Platform Status",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "platform_PlatformStatus{environment=\"$network\", metrics_node_id=~\".*\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Metric 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$name1",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{__name__=\"$name1\", environment=\"$network\", type=~\"$metric1_type\", metrics_node_id=~\".*\"}",
     "legendFormat": "node{{node}} {{ type }}"
    }
   ]
  },
  { "title": "Metric 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$name2",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{__name__=\"$name2\", environment=\"$network\", type=~\"$metric2_type\", metrics_node_id=~\".*\"}",
     "legendFormat": "node{{node}} {{ type }}"
    }
   ]
  },
  { "title": "Metric 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "$name3",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{__name__=\"$name3\", environment=\"$network\", type=~\"$metric3_type\", metrics_node_id=~\".*\"}",
     "legendFormat": "node{{node}} {{ type }}"
    }
   ]
  },
  { "title": "Metric 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "$name4",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{__name__=\"$name4\", environment=\"$network\", type=~\"$metric4_type\", metrics_node_id=~\".*\"}",
     "legendFormat": "node{{node}} {{ type }}"
    }
   ]
  },
  { "title": "Metric 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "$name5",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{__name__=\"$name5\", environment=\"$network\", type=~\"$metric5_type\", metrics_node_id=~\".*\"}",
     "legendFormat": "node{{node}} {{ type }}"
    }
   ]
  }
 ]
}