{
 "title": "Reconnects",
 "tags": [ "Platform" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec{environment!~\"nmt.*\"},environment)"
    }
   },
   { "name": "NodeID", "label": "NodeID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "directMem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "platform_directMemInMB{environment=\"$network\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "memTot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "platform_memTot{environment=\"$network\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Reconnect Learners",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "changes(Reconnect_startsReconnectAsReceiver_total{environment=\"$network\", node_id=~\"$NodeID\"}[1m])",
     "legendFormat": "{{node_id}} starts"
    },
    {
     "expr": "changes(Reconnect_endsReconnectAsReceiver_total{environment=\"$network\", node_id=~\"$NodeID\"}[1m])",
     "legendFormat": "{{node_id}} ends"
    }
   ]
  },
  {
   "title": "Reconnect Teachers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "changes(Reconnect_startsReconnectAsSender_total{environment=\"$network\", node_id=~\"$NodeID\"}[1m])",
     "legendFormat": "{{node_id}} starts"
    },
    {
     "expr": "changes(Reconnect_endsReconnectAsSender_total{environment=\"$network\", node_id=~\"$NodeID\"}[1m])",
     "legendFormat": "{{node_id}} ends"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 } }
 ]
}