{
 "title": "Signed States",
 "tags": [ "Platform" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "label": "Environment", "query": { "query": "label_values(environment)" } },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "issCount",
   "type": "stat",
   "description": "The number of nodes that currently disagree with the consensus hash",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ceil(rate(internal_issCount{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__rate_interval]))",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "oldestSignedStateSeconds",
   "type": "timeseries",
   "description": "The age of the oldest SignedState object in memory",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "internal_oldestSignedStateSeconds{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "oldestSignedStateSeconds",
   "type": "gauge",
   "description": "The age of the oldest SignedState object in memory",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(internal_oldestSignedStateSeconds{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "unsignedStates",
   "type": "timeseries",
   "description": "The average number of unsigned states awaiting signatures.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "platform_unsignedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "unsignedStates",
   "type": "gauge",
   "description": "The minimum, average, and maximum number of unsigned states reported. These use the min/mean/max metrics reported by each node and not just the average, so the min and max may be more extreme than shown on the average graph.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_unsignedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"min\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_unsignedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_unsignedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"max\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "signedStates",
   "type": "timeseries",
   "description": "The average number of fully signed states awaiting signatures.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "platform_signedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "signedStates",
   "type": "gauge",
   "description": "The minimum, average, and maximum number of fully signed states reported. These use the min/mean/max metrics reported by each node and not just the average, so the min and max may be more extreme than shown on the average graph.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_signedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"min\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_signedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_signedStates_count{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"max\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "totalNeverSignedStates/sec",
   "type": "timeseries",
   "description": "The changes in total number of states that did not receive enough signatures in the allowed time per second.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "increase(platform_totalNeverSignedStates_count_total{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__rate_interval])",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "totalNeverSignedStates",
   "type": "gauge",
   "description": "The total number of states that did not receive enough signatures in the allowed time.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(platform_totalNeverSignedStates_count_total{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "stateSignaturesGathered/sec",
   "type": "timeseries",
   "description": "The average number of state signatures gathered from other nodes per second.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "platform_stateSignaturesGathered_per_sec_hz{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "stateSignaturesGathers/sec",
   "type": "gauge",
   "description": "The minimum, average, and maximum number of state signatures gathered per second. These use the min/mean/max metrics reported by each node and not just the average, so the min and max may be more extreme than shown on the average graph.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_stateSignaturesGathered_per_sec_hz{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"min\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_stateSignaturesGathered_per_sec_hz{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_stateSignaturesGathered_per_sec_hz{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"max\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "stateSignatureAge",
   "type": "timeseries",
   "description": "The average difference in round number between state signatures and the most recent immutable state. Negative numbers mean the are being received early, large positive numbers mean signatures are being received late.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "platform_stateSignatureAge_rounds{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "stateSignatureAge",
   "type": "gauge",
   "description": "The average difference in round number between state signatures and the most recent immutable state. Negative numbers mean the are being received early, large positive numbers mean signatures are being received late.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_stateSignatureAge_rounds{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(avg_over_time(platform_stateSignatureAge_rounds{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}[$__range]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_stateSignatureAge_rounds{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}