{
 "title": "Threads & Queues",
 "tags": [ "Platform" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Environment", "label": "Environment", "query": { "query": "label_values(environment)" } },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "title": "Pre Consensus Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "preConsEvents",
   "type": "timeseries",
   "description": "The average number of events in the preconsensus queue (q1) waiting to be handled.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "internal_preConsEvents{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "preConsEvents",
   "type": "gauge",
   "description": "The average number of events in the preconsensus queue (q1) waiting to be handled.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_preConsEvents{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_preConsEvents{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_preConsEvents{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "preConsEvents Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "internal_thread_busy_thread_curr_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "preConsEvents Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_thread_curr_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_thread_curr_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_thread_curr_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Event Intake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "intakeQueue Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "internal_thread_busy_event_intake_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "intakeQueue Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_event_intake_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_event_intake_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_event_intake_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "intakeQueue", "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 } },
  { "title": "intakeQueue", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 } },
  { "title": "Event Creator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "eventCreator Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "internal_thread_busy_event_creator_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "eventCreator Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_event_creator_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_event_creator_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_event_creator_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "eventCreatorQueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "internal_event_creator_queueMaxSize{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "eventCreatorQueue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_event_creator_queueMaxSize{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_event_creator_queueMaxSize{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_event_creator_queueMaxSize{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "PreConsensus Event Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "eventWriter Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "internal_thread_busy_event_writer_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "eventWriter Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_event_writer_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_event_writer_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_event_writer_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Consensus Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "consEvents Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "internal_thread_busy_thread_cons_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "consEvents Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_thread_cons_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_thread_cons_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_thread_cons_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "consEvents", "gridPos": { "h": 8, "w": 16, "x": 0, "y": 69 } },
  {
   "title": "consEvents",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_consEventsMAX{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_consEventsMAX{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_consEventsMAX{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "State Hashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "stateHashSign Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "internal_thread_busy_state_hash_sign_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "stateHashSign Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_state_hash_sign_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_state_hash_sign_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_state_hash_sign_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Platform Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "statusStateMachine Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "internal_thread_busy_status_state_machine_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "statusStateMachine Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_status_state_machine_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_status_state_machine_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_status_state_machine_fraction{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}