{
 "title": "VirtualMap",
 "tags": [
  "Platform",
  "PlatformData"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec{environment!~\"nmt.*\"}, environment)"
    }
   },
   {
    "name": "Store",
    "label": "VirtualMap",
    "query": {
     "query": "metrics(virtual_map_vmap_size.*)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Size (entities count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "virtual_map_vmap_size_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Reads / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(virtual_map_vmap_queries_readEntities_$Store{environment=\"$Environment\"}[10m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Updates / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(virtual_map_vmap_queries_addedEntities_$Store{environment=\"$Environment\"}[10m]) + rate(virtual_map_vmap_queries_updatedEntities_$Store{environment=\"$Environment\"}[10m]) +\nrate(virtual_map_vmap_queries_removedEntities_$Store{environment=\"$Environment\"}[10m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node cache size, Mb",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_nodeCacheSizeMb_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "MerkleDb total file size, Mb",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "merkle_db_ds_files_totalSizeMb_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Copy hash time, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_hashDurationMs_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Copy flush time, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_flushDurationMs_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Flush backlog backpressure, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_flushBackpressureMs_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Family size backpressure, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_familySizeBackpressureMs_$Store{environment=\"$Environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}