{
 "title": "Entity Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Network", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(app_accountsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_accountsPercentUsed"
    },
    {
     "expr": "max(app_consGasPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_consGasPercentUsed"
    },
    {
     "expr": "max(app_contractsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_contractsPercentUsed"
    },
    {
     "expr": "max(app_filesPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_filesPercentUsed"
    },
    {
     "expr": "max(app_nftsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_nftsPercentUsed"
    },
    {
     "expr": "max(app_topicsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_topicsPercentUsed"
    },
    {
     "expr": "max(app_tokensPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_tokensPercentUsed"
    },
    {
     "expr": "max(app_schedulesPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_schedulesPercentUsed"
    }
   ]
  },
  {
   "title": "app_accountsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(app_accountsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_accountsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_accountsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_consGasPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(app_consGasPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_consGasPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_consGasPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_contractsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(app_contractsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_contractsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_contractsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_filesPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg(app_filesPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_filesPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_filesPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_nftsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(app_nftsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_nftsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_nftsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_topicsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg(app_topicsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_topicsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_topicsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_tokensPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "avg(app_tokensPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_tokensPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_tokensPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_schedulesPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "avg(app_schedulesPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_schedulesPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_schedulesPercentUsed{environment=\"$Network\"})"
    }
   ]
  }
 ]
}