version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - base_sample_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning/
    volumes:
      - ./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - base_sample_network
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/:/etc/loki/
    networks:
      - base_sample_network
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/promtail.yaml:/etc/promtail/config.yaml:ro  # Read-only mount for config
      - ../out/logs:/shared/logs:ro
    command:
      - "-config.file=/etc/promtail/config.yaml"
    depends_on:
      - loki
    ports:
      - "9080:9080"
    networks:
      - base_sample_network
networks:
  base_sample_network:
    driver: bridge