{
 "title": "Network Health",
 "tags": [ "Platform" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Environment", "label": "Environment", "query": { "query": "label_values(environment)" } },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Platform Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_PlatformStatus{environment=\"$Environment\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "healthyNetworkFraction",
   "type": "timeseries",
   "description": "The fraction (out of 1.0) of the network that is alive and healthy, weighted by consensus weight.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "platform_healthyNetworkFraction_fraction{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Current healthyNetworkFraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(platform_healthyNetworkFraction_fraction{environment=\"$Environment\", node_id=~\"$NodeID\", type=\"mean\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trans/sec",
   "type": "timeseries",
   "description": "The number of app transactions added to the hashgraph per second by each node via deduplicated events.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "platform_trans_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Avg trans/sec",
   "type": "gauge",
   "description": "The average number of app transactions added to the hashgraph per second by the network via deduplicated events.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_trans_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "secC2C",
   "type": "timeseries",
   "description": "The time from creating an event to knowing its consensus (in seconds).",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "platform_secC2C{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{ node_id }}"
    }
   ]
  },
  {
   "title": "secC2C",
   "type": "gauge",
   "description": "Of the secC2C values reported by each node, the minimum, average, and maximum.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "min(min_over_time(platform_secC2C{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_secC2C{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_secC2C{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "cEvents/sec",
   "type": "timeseries",
   "description": "The number of events per second created by each node in the network.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "platform_cEvents_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "cEvents/sec",
   "type": "gauge",
   "description": "The average number of events per second created by each node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_cEvents_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_cEvents_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_cEvents_per_sec{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "intakeQueue", "gridPos": { "h": 8, "w": 16, "x": 0, "y": 40 } },
  { "title": "intakeQueue", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 } },
  { "title": "consEvents", "gridPos": { "h": 8, "w": 16, "x": 0, "y": 48 } },
  {
   "title": "consEvents",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "min(min_over_time(internal_consEvents{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_consEvents{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_consEventsMAX{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "secTransH",
   "type": "timeseries",
   "description": "The average time to handle a consensus transaction in SwirldState.handleTransaction()",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "internal_secTransH{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Network secTransH",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_secTransH{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_secTransH{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_secTransH{environment=\"$Environment\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "preHandleMicros",
   "type": "timeseries",
   "description": "The average time it takes to perform preHandle.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "internal_preHandleMicros{environment=\"$Environment\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Network preHandleMicros",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_preHandleMicros{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_preHandleMicros{environment=\"$Environment\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_preHandleMicros{environment=\"$Environment\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}