{
 "title": "Node Software Important (Prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Networks", "query": { "query": "label_values(environment)" } },
   { "name": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "${Networks} TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(platform_secC2C{environment=\"$Networks\", type=\"mean\"})",
     "legendFormat": "{{__name__}} - {{ type }}"
    }
   ]
  },
  {
   "title": "secC2C avg all",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_secC2C{environment=\"$Networks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SecC2C - Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "platform_secC2C{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "SecC2C Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "platform_secC2C{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "{{__name__}} - {{type}}"
    }
   ]
  },
  {
   "title": "TransH_Per_sec   Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "internal_transH_per_sec{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "dupEvPercent Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_dupEvPercent{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "trans_per_sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_trans_per_sec{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "trans_per_event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_trans_per_event{environment=\"$Networks\", type=\"mean\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "sigStateHash Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_sigStateHash{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "writeQueueSizeRecordStream Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "app_writeQueueSizeRecordStream{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "conns Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_conns{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "CPU Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_cpuLoadSys{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "bytes_per_trans Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_bytes_per_trans{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "PlatformStatus Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_PlatformStatus{environment=\"$Networks\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "Q4 Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_q4{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "rounds_per_sec Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_rounds_per_sec{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "memFree Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_memFree{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "events_per_sec Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "platform_events_per_sec{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "secTransH Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_secTransH{environment=\"$Networks\", type=\"max\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "sec_per_sync2 Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_sec_per_sync2{environment=\"$Networks\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "sec_per_sync4 Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_sec_per_sync4{environment=\"$Networks\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "sec_per_sync3 Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_sec_per_sync3{environment=\"$Networks\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "sec_per_sync Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "internal_sec_per_sync{environment=\"$Networks\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  }
 ]
}