{
 "title": "JasperDB Details Single Node (Prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Networks", "query": { "query": "label_values(environment)" } },
   { "name": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "${Networks} Tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "internal_transH_per_sec{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${Networks} Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "internal_DiskspaceFree{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Open Databases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "jasper_db_jpdb_count{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Smart Contracts Internal Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Internal Node - Writes/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "jasper_db_internalNodeWrites_per_s_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}} - {{type}}"
    }
   ]
  },
  {
   "title": "Internal Node - Reads/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "jasper_db_internalNodeReads_per_s_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}} - {{type}}"
    }
   ]
  },
  {
   "title": "Internal Node - File Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "jasper_db_internalHashFileCount_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Internal Node - File Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "jasper_db_internalHashFileSizeMb_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Node - Merge Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jasper_db_internalHashLargeMergeTime_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jasper_db_internalHashMediumMergeTime_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jasper_db_internalHashSmallMergeTime_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Smart Contract - Leaves",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Smart Contract Leaf - Writes/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "jasper_db_leafWrites_per_s_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}} - {{type}}"
    }
   ]
  },
  {
   "title": "Smart Contract Leaf - Reads By Key/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "jasper_db_leafByKeyReads_per_s_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}} - {{ type }}"
    }
   ]
  },
  {
   "title": "Smart Contract Leaf - Reads By Path/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "jasper_db_leafByPathReads_per_s_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}} - {{ type }}"
    }
   ]
  },
  {
   "title": "Smart Contract Leaf - Leaf Data File Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "jasper_db_leafHKVFileCount_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key->Path Map File Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "leafKey", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Smart Contract Leaf - Leaf Data File Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "jasper_db_leafHKVFileSizeMb_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key->Path Map File Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "leafKeyToPathFileSizeMb_smartContractIterableKvStore",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "name:node$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Leaf Data Merge Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jasper_db_leafHKVLargeMergeTime_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jasper_db_leafHKVMediumMergeTime_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jasper_db_leafHKVSmallMergeTime_smartContractIterableKvStore{environment=\"$Networks\", node=\"$Node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Key->Path Map Merge Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "leafKeyToPathLargeMergeTime_smartContractIterableKvStore",
       "id": "1",
       "type": "avg"
      },
      {
       "field": "leafKeyToPathMediumMergeTime_smartContractIterableKvStore",
       "id": "6",
       "type": "avg"
      },
      {
       "field": "leafKeyToPathSmallMergeTime_smartContractIterableKvStore",
       "id": "7",
       "type": "avg"
      }
     ],
     "query": "name:node$Node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}