{
 "title": "Network Details (Prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Network", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_PlatformStatus{node=~\".*\", environment=\"$Network\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "Degraded?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_degraded{node=~\".*\", environment=\"$Network\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "healthyNetworkFraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "platform_healthyNetworkFraction_fraction{environment=\"$Network\", type=\"mean\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "issCount",
   "type": "timeseries",
   "description": "issCount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "internal_issCount{environment=\"$Network\"}",
     "legendFormat": "node{{node_id}}"
    }
   ]
  },
  {
   "title": "Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SecC2C",
   "type": "gauge",
   "description": "The average secC2C over this time interval",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_secC2C{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "description": "Transactions handled per second",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_trans_per_sec{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Per Event",
   "type": "gauge",
   "description": "Average number of transactions per event",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_trans_per_event{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GAS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(app_consGasPercentUsed{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "description": "Average Rounds per Second",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_rounds_per_sec{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EPS",
   "type": "gauge",
   "description": "Average Events Per Second",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_events_per_sec{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "gauge",
   "description": "The total JVM heap used",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_memTot{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Average CPU utlization",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(platform_cpuLoadSys{environment=\"$Network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "platform_memTot{metrics_node_id=~\".*\", type=\"mean\", environment=\"$Network\"}",
     "legendFormat": "node{{metrics_node_id}}"
    }
   ]
  },
  {
   "title": "GAS/ConsensusSec",
   "type": "timeseries",
   "description": "Average EVM gas used per second of consensus time",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_gasPerConsSec{environment=\"$Network\", type=\"mean\", node=~\".*\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "Smart Contract Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Smart Contract Data",
   "type": "timeseries",
   "description": "The number of smart contract key/value pairs (or leaves in the merkle tree)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "virtual_map_vMapSize_smartContractIterableKvStore{environment=\"$Network\", node=~\".*\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "Database File Counts",
   "type": "timeseries",
   "description": "Number of files used by the JasperDB, average over 10s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg(jasper_db_internalHashFileCount_smartContractIterableKvStore{environment=\"$Network\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "avg(jasper_db_leafHKVFileCount_smartContractIterableKvStore{environment=\"$Network\"})",
     "legendFormat": "__auto"
    },
    { "expr": "smartcontractitera", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hedera File Service Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gossip & Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SecC2C",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "platform_secC2C{environment=\"$Network\", type=\"mean\", node=~\".*\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  },
  {
   "title": "TPS per Node",
   "type": "timeseries",
   "description": "transH_per_sec",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "internal_transH_per_sec{environment=\"$Network\", type=\"mean\", node=~\".*\"}",
     "legendFormat": "node{{node}}"
    }
   ]
  }
 ]
}