/*
 * Copyright (C) 2022 Hedera Hashgraph, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hedera.node.app.spi.state;

import edu.umd.cs.findbugs.annotations.NonNull;
import edu.umd.cs.findbugs.annotations.Nullable;
import java.io.DataInput;
import java.io.IOException;

/**
 * Describes a method for parsing an object, typically from some binary format.
 *
 * <p>When using a {@link ReadableState} or {@link WritableState}, it is advisable to use natural
 * types and business objects as the keys and values. For example, you may use {@code Long} as the
 * key and {@code Account} as the value of a state. This makes the code very simple to implement,
 * understand, and test. However, every key and value stored in the system must be serializable to a
 * form that can be used both for storage and for hashing. The {@link Parser} and the {@link Writer}
 * parse from bytes and write into bytes, respectively.
 *
 * <p>Typically, a concrete implementation of this interface is not created. Instead, use one of the
 * static parser methods generated by the PBJ (protobuf for java) library.
 *
 * @param <T> The type of object to be parsed
 */
@FunctionalInterface
public interface Parser<T> {
    /**
     * Parsed an object from the {@link DataInput} and returns it.
     *
     * @param input The {@link DataInput} from which to read the data to construct an object
     * @return The parsed object. It must not return null.
     * @throws IOException If it is impossible to read from the {@link DataInput}
     */
    @Nullable
    T parse(@NonNull DataInput input) throws IOException;
}
