/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hedera_nativesupport_jni_Greeter */

#ifndef _Included_com_hedera_nativesupport_jni_Greeter
#define _Included_com_hedera_nativesupport_jni_Greeter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hedera_nativesupport_jni_Greeter
 * Method:    getGreeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hedera_nativesupport_jni_Greeter_getGreeting
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
