package com.swirlds.platform.cli;

import com.swirlds.cli.PlatformCli;
import com.swirlds.cli.utility.AbstractCommand;
import com.swirlds.cli.utility.SubcommandOf;
import com.swirlds.common.io.utility.FileUtils;
import picocli.CommandLine;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@CommandLine.Command(
		name = "clean",
		mixinStandardHelpOptions = true,
		description = "Delete all files generated by running the platform.")
@SubcommandOf(PlatformCli.class)
public final class CleanCommand extends AbstractCommand {
	/** The path to the sdk directory */
	private Path sdkPath;

	/**
	 * Set the path to state A.
	 */
	@CommandLine.Parameters(description = "the path to the first SignedState.swh that is being compared")
	private void setStateAPath(final Path sdkPath) {
		this.sdkPath = dirMustExist(sdkPath.toAbsolutePath());
	}

	@Override
	public Integer call() throws Exception {
		// logs
		FileUtils.deleteFiles(sdkPath, ".log");
		// metrics
		FileUtils.deleteFiles(sdkPath, ".csv");

		return 0;
	}
}
