{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Info & Debug Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"app-logs\"} != `TRACE`"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{log_level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Items Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_item_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total operations made",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_operation_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "How long it complete an operation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_operation_time_ns", "legendFormat": "__auto" }
   ]
  },
  { "title": "Comunication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Number of Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restapi_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restapi_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Avg Time ns",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restapi_request_avg_time_ns", "legendFormat": "{{type}}" },
    {}
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "restapi_requests_per_second_ops",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "internal_memFree", "legendFormat": "{{__name__}}" },
    { "expr": "internal_directMem", "legendFormat": "{{__name__}}" },
    { "expr": "internal_memTot", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "internal_cpuLoadProc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open Files Descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "internal_openFileDesc", "legendFormat": "__auto" }
   ]
  }
 ]
}