#  This is an intellij http requests file.
#  To use it, open the file and hit play on the desired request

### Get metrics
GET http://{{server}}:{{metrics-port}}/
Accept: application/text

###  POST request to create a new item
#  This request creates a new item in the inventory.
# Example:
# {
#   "description": "Example Item",
#   "sku": "123456",
#   "minimumStockLevel": 10,
#   "category": "Example Category"
# }
POST http://{{server}}:{{port}}/swirlds/api/items
Content-Type: application/json

{
  "description": "Example Item",
  "sku": "123456",
  "minimumStockLevel": 10,
  "category": "Example Category"
}

### GET request to retrieve all items
# This request retrieves all items from the inventory.
GET http://{{server}}:{{port}}/swirlds/api/items

###  GET request to retrieve an item by ID
# This request retrieves an item from the inventory by its ID.
GET http://localhost:8080/items/dda6d4f3-3941-4966-adea-6f047fb038ab

###  GET request to retrieve detailed inventory
# This request retrieves detailed inventory information.
GET http://localhost:8080/Inventories/

### POST request to create a new sale
# This request creates a new sale transaction.
# Example:
# {
#   "itemId": "123456",
#   "amount": 5,
#   "salePrice": 20.99
# }
POST http://{{server}}:{{port}}/swirlds/api/sales
Content-Type: application/json

{
"itemId": "123456",
"amount": 5,
"salePrice": 20.99
}

### POST request to create a new purchase
# This request creates a new purchase transaction.
# Example:
# {
#   "itemId": "123456",
#   "amount": 10,
#   "salePrice": 15.99
# }
POST http://{{server}}:{{port}}/swirlds/api/purchase
Content-Type: application/json

{
"itemId": "123456",
"amount": 10,
"buyPrice": 15.99
}
