### create wallet
POST http://{{server}}:{{port}}/swirlds/api/wallets
Content-Type: application/json

{}

### Get a wallet
GET http://{{server}}:{{port}}/swirlds/api/wallets/0
Accept: application/json

### get all wallets
GET http://{{server}}:{{port}}/swirlds/api/wallets
Accept: application/json

### Get balance
GET http://{{server}}:{{port}}/swirlds/api/balances/X
Accept: application/json


### create transfer
POST http://{{server}}:{{port}}/swirlds/api/transfers
Content-Type: application/json

{
  "from": "0",
  "to": "X",
  "amount": "1000000"

}

### Get metrics
GET http://{{server}}:{{metrics-port}}/
Accept: application/text
