package com.hedera.services.grpc.marshalling;

enum FixedFeeResult {
	ASSESSMENT_FINISHED,
	FRACTIONAL_FEE_ASSESSMENT_PENDING,
	ROYALTY_FEE_ASSESSMENT_PENDING,
	ASSESSMENT_FAILED_WITH_TOO_MANY_ADJUSTMENTS_REQUIRED
}
