// SPDX-License-Identifier: Apache-2.0
package com.swirlds.common.utility;

import static com.swirlds.common.utility.StackTrace.getStackTrace;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.regex.Pattern;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Unit tests for the {@link StackTrace} record.
 */
@DisplayName("StackTrace Test")
class StackTraceTest {

    /** Regular expression used to validate the first line of the stack trace generated below. */
    private static final Pattern FIRST_LINE_MATCHER = Pattern.compile(
            "(com|org|net)\\..*StackTraceTest\\.stackTraceTest\\(StackTraceTest.java:[0-9]+\\)",
            Pattern.CASE_INSENSITIVE);

    /**
     * Verifies the first line of the stack trace generated by the {@link StackTrace#getStackTrace()} utility method
     * properly ignores the first 2 stack frames.
     */
    @Test
    @DisplayName("Stack Trace Test")
    void stackTraceTest() {
        final String stackTrace = getStackTrace().toString();

        final String firstLine = stackTrace.split("\n")[0];
        assertTrue(
                FIRST_LINE_MATCHER.matcher(firstLine).matches(),
                "The first line of stack trace doesn't match expected. This may fail if the name of this class or test method changes.");
    }
}
