#!/usr/bin/env bash

SUFFIXES=(BRANCH BUILD_NUM BUILD_URL COMPARE_URL JOB PROJECT_REPONAME PROJECT_USERNAME PULL_REQUEST REPOSITORY_URL SHA1 TAG USERNAME WORKFLOW_ID)

for SUFFIX in ${SUFFIXES[@]}; do
  BUILTIN_VAR="CIRCLE_$SUFFIX"
  echo "$BUILTIN_VAR=${!BUILTIN_VAR}"
done
