#!/usr/bin/env bash

ENV_SCRIPT_PATH="${REPO}/.circleci/set-builtin-env.sh"
SUFFIXES=(BRANCH COMPARE_URL JOB PROJECT_REPONAME PROJECT_USERNAME PULL_REQUEST REPOSITORY_URL SHA1 TAG USERNAME WORKFLOW_ID)

if [ -f $ENV_SCRIPT_PATH ]; then
  . $ENV_SCRIPT_PATH
else
  for SUFFIX in ${SUFFIXES[@]}; do
    BUILTIN_VAR="CIRCLE_$SUFFIX"
    echo "export $BUILTIN_VAR=${!BUILTIN_VAR}" >> $ENV_SCRIPT_PATH
  done
  chmod +x $ENV_SCRIPT_PATH
  cat $ENV_SCRIPT_PATH
fi
