{
 "title": "E2E Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Publisher - Total TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "Total TPS"
    }
   ]
  },
  {
   "title": "Publisher - HCS  Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_sum{status=\"SUCCESS\", type=\"CONSENSUS_SUBMIT_MESSAGE\"}[5m])) / sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"SUCCESS\", type=\"CONSENSUS_SUBMIT_MESSAGE\"}[5m]))",
     "legendFormat": "Latency (HCS)"
    }
   ]
  },
  {
   "title": "Publisher - Non-Successful TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "Total Non-Successful TPS"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"PlatformTransactionNotCreated\"}[$__rate_interval]))",
     "legendFormat": "Error - PlatformTransactionNotCreated"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\",status!=\"PlatformTransactionNotCreated\",status!=\"TransactionExpired\",status!=\"HederaNetworkException\",status!=\"Busy\"}[$__rate_interval]))",
     "legendFormat": "Error - Others"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\",status=\"TransactionExpired\"}[$__rate_interval]))",
     "legendFormat": "Error - TransactionExpired"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\",status=\"HederaNetworkException\"}[$__rate_interval]))",
     "legendFormat": "Error - HederaNetworkException"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\",status=\"Busy\"}[$__rate_interval]))",
     "legendFormat": "Error - Busy"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\",status=\"DuplicateTransaction\"}[$__rate_interval]))",
     "legendFormat": "Error-DuplicateTransaction"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status!=\"SUCCESS\",status=\"Exception\"}[$__rate_interval]))",
     "legendFormat": "Error-Exception"
    }
   ]
  },
  {
   "title": "Publisher - HTS  Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_sum{status=\"SUCCESS\", type=\"CRYPTO_TRANSFER\"}[5m]))/ sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"SUCCESS\", type=\"CRYPTO_TRANSFER\"}[5m]))",
     "legendFormat": "Latency (HTS)"
    }
   ]
  },
  {
   "title": "E2E - Total TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mn_hcs_seconds_count{status=\"SUCCESS\"}[5m])) + sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "Total TPS"
    },
    {
     "expr": "sum(rate(hedera_mn_hcs_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "Total TPS (HCS)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "Total TPS (HTS)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"CRYPTO\" }[5m]))",
     "legendFormat": "TPS - CRYPTO"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"TOKEN\" }[5m]))",
     "legendFormat": "TPS - TOKEN"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"BOTH\" }[5m]))",
     "legendFormat": "TPS - BOTH"
    }
   ]
  },
  {
   "title": "E2E -  Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mn_hcs_seconds_sum{status=\"SUCCESS\"}[5m])) / sum(rate(hedera_mn_hcs_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "Latency (HCS)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_sum{status=\"SUCCESS\"}[5m])) / sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "Latency (HTS)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_sum{status=\"SUCCESS\", attribute=\"CRYPTO\"}[5m])) / sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"CRYPTO\"}[5m]))",
     "legendFormat": "Latency (HTS - CRYPTO)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_sum{status=\"SUCCESS\", attribute=\"TOKEN\"}[5m])) / sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"TOKEN\"}[5m]))",
     "legendFormat": "Latency (HTS - TOKEN)"
    }
   ]
  },
  {
   "title": "E2E - HCS: TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mn_hcs_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "SUM"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"64\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 64)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"128\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 128)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"256\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 256)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"512\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 512)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"2048\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 2048)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"6000\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 6000)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_count{attribute=\"1300\",status=\"SUCCESS\"}[5m])",
     "legendFormat": "TPS (MsgSize 1300)"
    }
   ]
  },
  {
   "title": "E2E - HCS: Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hedera_mn_hcs_seconds_sum{attribute=\"64\"}[5m]) / rate(hedera_mn_hcs_seconds_count{attribute=\"64\"}[5m])",
     "legendFormat": "Latency (MsgSize 64)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_sum{attribute=\"256\"}[5m]) / rate(hedera_mn_hcs_seconds_count{attribute=\"256\"}[5m])",
     "legendFormat": "Latency (MsgSize 256)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_sum{attribute=\"512\"}[5m]) / rate(hedera_mn_hcs_seconds_count{attribute=\"512\"}[5m])",
     "legendFormat": "Latency (MsgSize 512)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_sum{attribute=\"2048\"}[5m]) / rate(hedera_mn_hcs_seconds_count{attribute=\"2048\"}[5m])",
     "legendFormat": "Latency (MsgSize 2048)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_sum{attribute=\"6000\"}[5m]) / rate(hedera_mn_hcs_seconds_count{attribute=\"6000\"}[5m])",
     "legendFormat": "Latency (MsgSize 6000)"
    },
    {
     "expr": "rate(hedera_mn_hcs_seconds_sum{attribute=\"128\"}[5m]) / rate(hedera_mn_hcs_seconds_count{attribute=\"128\"}[5m])",
     "legendFormat": "Latency (MsgSize 128)"
    }
   ]
  },
  {
   "title": "E2E - HTS : TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\"}[5m]))",
     "legendFormat": "TPS - TOTAL"
    },
    {
     "expr": "rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"CRYPTO\"}[5m])",
     "legendFormat": "TPS - CRYPTO"
    },
    {
     "expr": "rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"TOKEN\"}[5m])",
     "legendFormat": "TPS - TOKEN"
    },
    {
     "expr": "rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"BOTH\"}[5m])",
     "legendFormat": "TPS - BOTH"
    }
   ]
  },
  {
   "title": "E2E - HTS : Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_sum{status=\"SUCCESS\", attribute=\"CRYPTO\"}[5m])) / sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"CRYPTO\"}[5m]))",
     "legendFormat": "Latency (CRYPTO)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_sum{status=\"SUCCESS\", attribute=\"TOKEN\"}[5m])) / sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"TOKEN\"}[5m]))",
     "legendFormat": "Latency (TOKEN)"
    },
    {
     "expr": "sum(rate(hedera_mn_hts_seconds_sum{status=\"SUCCESS\", attribute=\"BOTH\"}[5m])) / sum(rate(hedera_mn_hts_seconds_count{status=\"SUCCESS\", attribute=\"BOTH\"}[5m]))",
     "legendFormat": "Latency (BOTH)"
    }
   ]
  },
  {
   "title": "Publisher - HCS: TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"SUCCESS\", type=\"CONSENSUS_SUBMIT_MESSAGE\"}[5m]))",
     "legendFormat": "Total HCS TPS"
    }
   ]
  },
  {
   "title": "Publisher  - HTS: TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"SUCCESS\", scenario=\"CryptoTransfer\", type=\"CRYPTO_TRANSFER\"}[5m])",
     "legendFormat": "TPS - CRYPTO"
    },
    {
     "expr": "rate(hedera_mirror_monitor_publish_submit_seconds_count{status=\"SUCCESS\", scenario=\"TokenTransfer\", type=\"CRYPTO_TRANSFER\"}[5m])",
     "legendFormat": "TPS - TOKEN"
    }
   ]
  },
  {
   "title": "E2E Subscribe - HTS TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{application=\"hedera-mirror-monitor\",scenario=\"CryptoTransfer\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m])",
     "legendFormat": "TPS - CRYPTO"
    },
    {
     "expr": "rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\",scenario=\"HTSTransferTOKENSub\"}[5m])",
     "legendFormat": "TPS - TOKEN"
    },
    {
     "expr": "rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\",scenario=\"HTSTransferBOTHSub\"}[5m])",
     "legendFormat": "TPS - BOTH"
    },
    {
     "expr": "rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{application=\"hedera-mirror-monitor\",scenario=\"SubmitMessage\",type=\"CONSENSUS_SUBMIT_MESSAGE\"}[5m])",
     "legendFormat": "TPS - HCS"
    }
   ]
  },
  {
   "title": "E2E Subscribe - HTS Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_sum{application=\"hedera-mirror-monitor\",scenario=\"CryptoTransfer\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m])) / sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{application=\"hedera-mirror-monitor\",scenario=\"CryptoTransfer\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m]))",
     "legendFormat": "Latency - CRYPTO"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_sum{application=\"hedera-mirror-monitor\",scenario=\"CryptoTransfer\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m])) / sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{application=\"hedera-mirror-monitor\",scenario=\"CryptoTransfer\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m]))",
     "legendFormat": "Latency - TOKEN"
    },
    {
     "expr": "sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_sum{application=\"hedera-mirror-monitor\",scenario=\"HTSTransferBOTHSub\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m])) / sum(rate(hedera_mirror_monitor_subscribe_e2e_seconds_count{application=\"hedera-mirror-monitor\",scenario=\"HTSTransferBOTHSub\",subscriber=\"RestSubscriber\",type=\"CRYPTO_TRANSFER\"}[5m]))",
     "legendFormat": "Latency - BOTH"
    }
   ]
  }
 ]
}