##
# Copyright (C) 2022-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "ZXF: [Node] FSTS Daily (Interval: 6)"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout."
        required: true
        type: string
      branch-name:
        description: ""
        required: false
        type: string
      concurrency-group:
        description: "The concurrency group name to limit simultaneous workflows."
        required: false
        type: string

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.event.inputs.concurrency-group || format('{0}-{1}-flow-jrs-daily-interval-groups', github.ref_name, github.sha) }}

# Panel Definition & Timings:
# "configs/services/suites/daily/GCP-Daily-Services-MinStake-4N.json"                           ----         50m
# "configs/services/suites/daily/GCP-Daily-Services-SimilarStake-4N.json"                       ----         50m
# "configs/services/suites/daily/GCP-Daily-Services-UnevenStake-4N.json"                        ----         50m
# "configs/services/suites/daily/GCP-Daily-Services-ZeroStake-4N.json"                          ----         50m
# "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-MinStake-5N.json"       ----         30m
# "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-SimilarStake-5N.json"   ----         30m
# "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-UnevenStake-5N.json"    ----         30m
# "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-ZeroStake-5N.json"      ----         30m
#
#   TOTAL RUN TIME:             321 minutes, 5.3 hours
#
#   Two parallel jobs:
#
#     minstake-4n -> similarstake-4n -> unevenstake-4n -> zerostake-4n
#     restartwithnewnodes-minstake-5n ->

jobs:
  minstake-4n:
    name: MinStake-4N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-MinStake-4N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}

  similarstake-4n:
    name: SimilarStake-4N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-SimilarStake-4N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
    needs:
      - minstake-4n

  unevenstake-4n:
    name: UnevenStake-4N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-UnevenStake-4N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
    needs:
      - similarstake-4n

  zerostake-4n:
    name: ZeroStake-4N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-ZeroStake-4N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
    needs:
      - unevenstake-4n

  restartwithnewnodes-minstake-5n:
    name: RestartWithNewNodes-MinStake-5N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-MinStake-5N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}

  restartwithnewnodes-similarstake-5n:
    name: RestartWithNewNodes-SimilarStake-5N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-SimilarStake-5N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
    needs:
      - restartwithnewnodes-minstake-5n

  restartwithnewnodes-unevenstake-5n:
    name: RestartWithNewNodes-UnevenStake-5N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-UnevenStake-5N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
    needs:
      - restartwithnewnodes-similarstake-5n

  restartwithnewnodes-zerostake-5n:
    name: RestartWithNewNodes-ZeroStake-5N
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ !cancelled() && always() }}
    with:
      ref: ${{ github.event.inputs.ref }}
      branch-name: ${{ github.event.inputs.branch-name }}
      hedera-tests-enabled: true
      use-branch-for-slack-channel: true
      panel-config: "configs/services/suites/daily/GCP-Daily-Services-RestartWithNewNodes-ZeroStake-5N.json"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
    needs:
      - restartwithnewnodes-unevenstake-5n
