##
# Copyright (C) 2022-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "Platform: PR Extended Checks"
on:
  workflow_dispatch:
    slack-results-channel:
      description: "Slack Test Result Channel:"
      required: false
      type: string
      default: "regression-test"
    slack-summary-channel:
      description: "Slack Summary Channel:"
      required: false
      type: string
      default: "regression-test"
    java-version:
      description: "Java JDK Version:"
      type: string
      required: false
      default: "21.0.4"
    java-distribution:
      description: "Java JDK Distribution:"
      type: string
      required: false
      default: "temurin"
    gradle-version:
      description: "Gradle Version:"
      type: string
      required: false
      default: "wrapper"

defaults:
  run:
    shell: bash

concurrency:
  group: pr-ext-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  reconnect:
    name: Reconnect
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    with:
      panel-config: "configs/suites/daily/4N/GCP-Daily-Reconnect-4N.json"
      ref: ${{ github.event.inputs.ref || github.ref }}
      branch-name: ${{ github.ref_name }}
      slack-results-channel: ${{ github.event.inputs.slack-results-channel }}
      slack-summary-channel: ${{ github.event.inputs.slack-summary-channel }}
      java-version: ${{ github.event.inputs.java-version || '21.0.4' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
      use-branch-for-slack-channel: false
      custom-job-name: "Custom"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
  restart:
    name: Restart
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    with:
      panel-config: "configs/suites/daily/4N/GCP-Daily-Restart-4N.json"
      ref: ${{ github.event.inputs.ref || github.ref }}
      branch-name: ${{ github.ref_name }}
      slack-results-channel: ${{ github.event.inputs.slack-results-channel }}
      slack-summary-channel: ${{ github.event.inputs.slack-summary-channel }}
      java-version: ${{ github.event.inputs.java-version || '21.0.4' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
      use-branch-for-slack-channel: false
      custom-job-name: "Custom"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
  dynamic-freeze:
    name: DynamicFreeze
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    with:
      panel-config: "configs/suites/daily/4N/GCP-Daily-DynamicFreeze-4N.json"
      ref: ${{ github.event.inputs.ref || github.ref }}
      branch-name: ${{ github.ref_name }}
      slack-results-channel: ${{ github.event.inputs.slack-results-channel }}
      slack-summary-channel: ${{ github.event.inputs.slack-summary-channel }}
      java-version: ${{ github.event.inputs.java-version || '21.0.4' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
      use-branch-for-slack-channel: false
      custom-job-name: "Custom"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
  NewNodesSimilarStake:
    name: NewNodesSimilarStake
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    with:
      panel-config: "configs/suites/daily/5N/GCP-Daily-RestartWithNewNodes-SimilarStake-5N.json"
      ref: ${{ github.event.inputs.ref || github.ref }}
      branch-name: ${{ github.ref_name }}
      slack-results-channel: ${{ github.event.inputs.slack-results-channel }}
      slack-summary-channel: ${{ github.event.inputs.slack-summary-channel }}
      java-version: ${{ github.event.inputs.java-version || '21.0.4' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
      use-branch-for-slack-channel: false
      custom-job-name: "Custom"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
