##
# Copyright (C) 2022-2023 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "Z-Platform XCron: Develop Daily Snapshot"
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write

jobs:
  trigger-task:
    name: Trigger Daily Run
    runs-on: [self-hosted, Linux, small, scheduler, ephemeral]
    steps:
      - name: Display Branch Information
        run: |
          printf "Ref: \t\t${{ github.ref }}"
          printf "Head Ref: \t\t${{ github.head_ref }}"
          printf "Ref Name: \t${{ github.ref_name }}"
          printf "Commit SHA: \t${{ github.sha }}"
  develop-daily-snapshot:
    name: "Develop"
    uses: ./.github/workflows/platform-zxc-release-internal.yaml
    needs:
      - trigger-task
    with:
      java-version: 17.0.3
      java-distribution: temurin
      deployment-profile: develop-daily-snapshot
      version-policy: snapshot-locked
      custom-job-label: "Snapshot / Daily"
      dry-run-enabled: false
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
